### ISSUE TITLE
Change email - settings

### ISSUE THREAD

**Issue by mathiassond** [internxt/drive-mobile#203]
[Feature request] - ability to change email address in settings.

**Comment by claell** [comment]
@PixoDev should the be closed, as it's a feature request?

**Comment by PixoDev** [comment]
Hey, actually this feature is something we are actively working on, so at some point we will add it at least to the web version.

Im closing this for now ✌️

**Comment by claell** [comment]
Hope we can finally see public issue tracking for internxt (including features), ASAP 😄
