### ISSUE TITLE
Unable to see total storage of my folder in the website

### ISSUE THREAD

**Issue by connectsid00** [internxt/drive-mobile#223]
Hi, I recently tried to upload 15GB of folder, after 2.5 hours my upload stopped and I am unable to see how much I have uploaded in the folder? This just sucks, I don't even know if the files are fully uploaded or not, I need to manually calculate the files now. This is very bad drive guys. There is literally no option to see the total folder size I have uploaded currently

<img width="1058" alt="image" src="https://github.com/internxt/drive-mobile/assets/156069865/791cf678-dae3-47e1-9530-f428916a5049">

<img width="437" alt="image" src="https://github.com/internxt/drive-mobile/assets/156069865/db21c207-49b3-4977-b23a-9350d3434507">

**Comment by PixoDev** [comment]
Hey, please reach us at hello@internxt.com and we will give this a look, but please don't open this kind of issues in this repository as we cannot provide support to users over here, and this is the Mobile app repository, what you are sharing is the web version.
