### ISSUE TITLE
Github codebase and releases have not been updated in line with the Google Play release

### ISSUE THREAD

**Issue by AdrienChatelain** [internxt/drive-mobile#228]
The releases on this repo are significantly out of date compared to the Google Play releases, and so the app is not truly open source.

Currently the Google Play store version is 1.5.34 (4) - updated 6th Feb 2024
The most recent Github release is v1.5.31 from Oct 17, 2023.
The most recent commits are ~2 months old (c. January 2024).

**Comment by fvsegarra** [comment]
We use Expo. Hence, we don't always need to make an actual app store release to update the app. We often just push the updates remotely through Expo
