### ISSUE TITLE
Proposal: accessing specific files and folders to be available offline

### ISSUE THREAD

**Issue by jlghub** [internxt/drive-mobile#59]
choosing specific files and folders to be available offline

**Comment by jlghub** [comment]
Hi all, Any news on this topic?

**Comment by jlghub** [comment]
We really need this feature. Have you got it in your roadmap?

**Comment by AlexMenor** [comment]
Hi @jlghub, what do you mean exactly? Files are already available offline

**Comment by PixoDev** [comment]
Hey,

Thank you for your feedback, however we are not using Github issues for feature requests this time, we are discussing about using a public roadmap or something similar for this kind of things, we will let you know once we have something ready!

Closing this one, we will track the issues labeled as "feature request"

Have a nice day!
