### ISSUE TITLE
Proposal: Other security layer to open app with "little code" of 4 numbers (for example)

### ISSUE THREAD

**Issue by jlghub** [internxt/drive-mobile#60]
"Little code to open app": Will it be possible to add a "little code" of 4 numbers for example, just as another security control to access to the files in mobile (or even in desktop)

**Comment by PixoDev** [comment]
Hey,

Thank you for your feedback, however we are not using Github issues for feature requests this time, we are discussing about using a public roadmap or something similar for this kind of things, we will let you know once we have something ready!

Closing this one, we will track the issues labeled as "feature request"

Have a nice day!
