### ISSUE TITLE
Android App inclusion to F-Droid App Store.

### ISSUE THREAD

**Issue by b3pio** [internxt/drive-mobile#64]
Being open-sourced, inclusion on F-Droid app store would be a great addition, if not the main F-Droid repo then consider adding to IzzyOnDroid repo.
Personally I'd also like to see you consider completely removing the Google Trackers _(Firebase Analytics, AdMob etc)_ or at least replacing with privacy respecting analytics trackers in future versions please.

**Comment by AlexMenor** [comment]
Hey @b3pio, it's true that we don't have published the app yet in F-Droid, but you can search "internxt apk" and you will find other stores.

We'll consider publishing it in F-Droid though.

**Comment by b3pio** [comment]
That's great @AlexMenor, even publishing on the IzzyOnDroid f-droid repo would be a good start as you cannot always trust other sources of apk's such as apkpure etc. 

My other question is the offending libs being enabled, which is of course discouraged for FOSS builds:
* Google AdMob
* Google Firebase Analytics

**Comment by AlexMenor** [comment]
Agree with you @b3pio. We are working on it.

Thanks for your feedback!

**Comment by b3pio** [comment]
> Agree with you @b3pio. We are working on it.
> 
> Thanks for your feedback!

Great!
Also for example, replacement of Google Analytics you can look at an alternative [Matomo](https://github.com/matomo-org/matomo) which is privacy friendly, self-hosted and FOSS.

**Comment by b3pio** [comment]
@AlexMenor Any further developments on this? Would be great to also compile app releases here on github as well for those of us whom don't have google play / play services on our devices.

**Comment by AlexMenor** [comment]
Yes @b3pio. We have many things going on right now but we keep this in mind.

**Comment by b3pio** [comment]
Maybe Izzy @IzzySoft can help you to publish at least on his repository to start with? @AlexMenor

**Comment by IzzySoft** [comment]
Currently a bit difficult:

* there are no releases
* and thus no APK files attached to them
* I could not find any screenshots
* or even an app description

I could take another look if the above is solved. For description/screenshots, ideally establish [Fastlane Structures](https://gitlab.com/-/snippets/1895688) – my repo can work with this, F-Droid does, and "Fastlane Supply" works with other places like Play or Apple store, so you cover many things at once.

**Comment by AlexMenor** [comment]
Hi everyone, i've been talking with the team about this and i've learnt that there are stores that already list this app:
- https://x-cloud.en.aptoide.com/app
- https://apkpure.com/internxt-secure-cloud-storage/com.internxt.cloud
- https://apkcombo.com/internxt-secure-cloud-storage/com.internxt.cloud/
- https://apkfab.com/internxt-encrypted-cloud-storage/com.internxt.cloud

Is there anything else we should do?

**Comment by IzzySoft** [comment]
@AlexMenor as the question was specifically about F-Droid (the place for FOSS apps), none of the stores you mention can substitute. F-Droid makes sure the code base complies with FOSS principles, then builds the APK from exactly that codebase (including multiple levels of checks to make sure nothing proprietary slips in). So there's an additional level of trust, as an "independent party" checked it (nothing is perfect, but so far it works well).

So please see my previous comment: F-Droid builds from tags/releases, so it would need your releases tagged. It would also need app description and ideally screenshots – which is best done by establishing [Fastlane structures](https://gitlab.com/-/snippets/1895688) in your repo (for starters, en-US `short_description.txt` and `full_description` will do, but adding some screenshots on top is highly recommended).

The criteria of [my own repo](https://apt.izzysoft.de/fdroid), which @b3pio mentioned, are a little less strict, and my updater just picks the APKs attached to the releases as I have no capacities to set up a full build system here. It often serves as stepping stone for apps on their way to F-Droid, as integration is faster and that way they can check if they pass the tests (there's an overlap in the scanning process, so you can see parts of F-Droid's scan results in advance). You can find [details on that here](https://gitlab.com/IzzyOnDroid/repo).

In case you didn't hear about F-Droid before, here's an introductory article written by me: [F-Droid: The privacy-friendly alternative to Google Play Store](https://android.izzysoft.de/articles/named/fdroid-intro-1).

**Comment by pc00per** [comment]
Been waiting for fdroid release, as I don't run google play services & can't rely on third party APK sideloads.

**Comment by noticons** [comment]
I am looking for this, too. Coming out on F-Droid is a way of showing the Open Source and privacy focused nature of Internxt. The privacy focused community is moving to communities like F-Droid over other appstores. Internxt would put themselves where they need to be (and it would be just one more argument for why folks in the community should move their data to Internxt).

**Comment by julianfairfax** [comment]
> > @AlexMenor as the question was specifically about F-Droid (the place for FOSS apps), none of the stores you mention can substitute. F-Droid makes sure the code base complies with FOSS principles, then builds the APK from exactly that codebase (including multiple levels of checks to make sure nothing proprietary slips in). So there's an additional level of trust, as an "independent party" checked it (nothing is perfect, but so far it works well).
> > So please see my previous comment: F-Droid builds from tags/releases, so it would need your releases tagged. It would also need app description and ideally screenshots – which is best done by establishing [Fastlane structures](https://gitlab.com/-/snippets/1895688) in your repo (for starters, en-US `short_description.txt` and `full_description` will do, but adding some screenshots on top is highly recommended).
> > The criteria of [my own repo](https://apt.izzysoft.de/fdroid), which @b3pio mentioned, are a little less strict, and my updater just picks the APKs attached to the releases as I have no capacities to set up a full build system here. It often serves as stepping stone for apps on their way to F-Droid, as integration is faster and that way they can check if they pass the tests (there's an overlap in the scanning process, so you can see parts of F-Droid's scan results in advance). You can find [details on that here](https://gitlab.com/IzzyOnDroid/repo).
> > In case you didn't hear about F-Droid before, here's an introductory article written by me: [F-Droid: The privacy-friendly alternative to Google Play Store](https://android.izzysoft.de/articles/named/fdroid-intro-1).
> 
> Thank you for taking the time @IzzySoft, we'll look into it

Have you had the time to do this? It would at least be nice if you could upload the releases to GitHub releases so Izzy can pull the APKs into his repo and people like me who go through the effort of having their own can too. Obviously it'll be nice to remove the dependency on Google Play Services and merge it directly into F-Droid, but being able to at least install it from outside the Play Store would already be a big step in the right direction.

**Comment by julianfairfax** [comment]
Or at least provide the values for the /env/.env.production.json file. I literally can't build this myself at all because I don't know what these values are supposed to be. So the only possible method of obtaining this app is to download it from the Google Play Store.

**Comment by MalteKiefer** [comment]
Can you please add the apk to the releases and I will add it to my repo:

https://repo.beli3ver.de

Thanks

**Comment by PixoDev** [comment]
Hi, we are working on an automated building / signing / submitting workflow, and we will probably include F-Droid support since many users are requesting it.

In the meantime, we removed Segment and Firebase dependencies from the app, you can see the up to date Exodus report here https://reports.exodus-privacy.eu.org/es/reports/292023/

I'll give a look at @IzzySoft provided documentation and report back soon

Thanks!

**Comment by IzzySoft** [comment]
Size ≤ 30M √ a FOSS license √ – so it seems just the APK is missing so I could pick it. For some background etc. you [can see here](https://gitlab.com/IzzyOnDroid/repo/) – where also most of the code running the repo is available.

**Comment by julianfairfax** [comment]
> Size ≤ 30M √ a FOSS license √ – so it seems just the APK is missing so I could pick it.

Hey @PixoDev, any plans to do this?

**Comment by PixoDev** [comment]
Hey,

As I commented here:

> Hi, we are working on an automated building / signing / submitting workflow, and we will probably include F-Droid support since many users are requesting it.
> 
> In the meantime, we removed Segment and Firebase dependencies from the app, you can see the up to date Exodus report here https://reports.exodus-privacy.eu.org/es/reports/292023/
> 
> I'll give a look at @IzzySoft provided documentation and report back soon
> 
> Thanks!


We are planning to provide F-Droid support via automated building, but we are facing some problems due to old dependencies that needs to be addressed first in order to automate all the building/signing/submitting process.

I'll report over here once I have some progress on this.

**Comment by julianfairfax** [comment]
> Hey,
> 
> As I commented here:
> 
> > Hi, we are working on an automated building / signing / submitting workflow, and we will probably include F-Droid support since many users are requesting it.
> > In the meantime, we removed Segment and Firebase dependencies from the app, you can see the up to date Exodus report here https://reports.exodus-privacy.eu.org/es/reports/292023/
> > I'll give a look at @IzzySoft provided documentation and report back soon
> > Thanks!
> 
> We are planning to provide F-Droid support via automated building, but we are facing some problems due to old dependencies that needs to be addressed first in order to automate all the building/signing/submitting process.
> 
> I'll report over here once I have some progress on this.

In the meantime can you release the APKs you upload to the Play Store on this GitHub repository in the releases section?

**Comment by PixoDev** [comment]
Ok, so I created a new release, can be found here => https://github.com/internxt/drive-mobile/releases/tag/v1.5.18

The release contains a signed APK, please, let me know if you need anything else from my side in order to make it work until we automatize this.

Thanks!

**Comment by b3pio** [comment]
Can you please create signed apk for latest release by any chance?

> Ok, so I created a new release, can be found here => https://github.com/internxt/drive-mobile/releases/tag/v1.5.18
> 
> The release contains a signed APK, please, let me know if you need anything else from my side in order to make it work until we automatize this.
> 
> Thanks!

**Comment by AdrienChatelain** [comment]
Bumping this - an F-Droid release would be much appreciated and allow users to stick to open source software on android, and avoid using potentially dodgy ripped APK sites. If it's too difficult, is it possible to revisit adding it to the IzzyOnDroid repo as above?
I imagine you could more or less copy the Google Play description and screenshots to [Fastlane structures](https://gitlab.com/-/snippets/1895688) for now if you wish to get it up and running with minimal effort.

**Comment by IzzySoft** [comment]
> adding it to the IzzyOnDroid repo as above?

I don't think so. The last APK file I see attached to a release is about 130 MB – per-app limit in my repo is 30 MB. So this is way too big.
