### ISSUE TITLE
Feature Request - List APK on F-Droid

### ISSUE THREAD

**Issue by miladmohammadint** [internxt/drive-mobile#75]
Would be great if internxt drive was available on F-Droid and the website for those of us looking to move away from Google services. Thanks!

**Comment by mvozzo** [comment]
> Would be great if internxt drive was available on F-Droid and the website for those of us looking to move away from Google services. Thanks!

I support this request +100

**Comment by b3pio** [comment]
We have this issue/discussion open at #64 already if you want to add support for this request
