### ISSUE TITLE
iOS Version 1.5.6: Bug in home view when deleting items

### ISSUE THREAD

**Issue by RuedigerErdmann** [internxt/drive-mobile#78]
When trying to delete an item in home view a message confirms that the item has been deleted, but the item is still there after it.

**Comment by PixoDev** [comment]
Hey

We released some updates since that version, can you confirm us if the bug still exists in the current version? (1.5.14)

Also, if you refresh the view, the item still exists?

If you provide us a screen recording or something like that it will help us to track the problem easily

Thanks!

**Comment by RuedigerErdmann** [comment]
Hi, yes, everything's fine now, thanks :)
