### ISSUE TITLE
Release app on fdroid ?

### ISSUE THREAD

**Issue by Jrchintu** [internxt/drive-mobile#83]
https://f-droid.org is a catalog service for foss apps and a dedicated community for android apps. Are there any plans to release android app on fdroid ?

**Comment by b3pio** [comment]
Have open issue about F-droid inclusion here #64 @Jrchintu

**Comment by Jrchintu** [comment]
> Have open issue about F-droid inclusion here #64 @Jrchintu

Thanks, @b3pio sorry for not checking that. I consider closing this issue and will continue discussion on thread #64
