### ISSUE TITLE
iOS Photo sync doesn't work

### ISSUE THREAD

**Issue by devhawkio** [internxt/drive-mobile#90]
Much like the desktop sync app, the iOS photo sync does not work at all. Only one photo syncs an hour, if you leave the screen open, otherwise nothing is uploaded.

**Comment by PixoDev** [comment]
Hey we released an entire rebuild of the Internxt Photos sync system (1.5.14), can you please update your app and let me know if it's working now?

You can find the PR of the rebuild here if you are interested:
https://github.com/internxt/drive-mobile/pull/101

Thanks!

**Comment by PixoDev** [comment]
Closing, no response

**Comment by ibastevan** [comment]
I can confirm this will only sync when left on and syncing is very slow. If this is supposed to be able to sync in the background then it’s not working.
Thanks

iPhone 13
iOS 16.2
